# Generated by Django 2.1.5 on 2023-04-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20230403_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=123, unique=True),
        ),
    ]
